server:
  port: 8081

spring:
  application:
    name: ojy-bulletin-service

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password:

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false