server:
  port: 0

spring:
  application:
    name: ojy-bulletin-service

  datasource:
    url: jdbc:postgresql://localhost:5432/ohjooyeo
    driver-class-name: org.postgresql.Driver
    username: postgres
    password:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show-sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false

